/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pharmacy.gui;

import com.pharmacy.dao.SellingDAO;
import com.pharmacy.model.SellingPerUnit;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class InvoiceUnit extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceUnit
     */
     public String invoice = "";
    public InvoiceUnit() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public InvoiceUnit(String s) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        showProduct();
        this.invoice = s;
        System.out.println("invoice is: " + this.invoice);

        List<SellingPerUnit> sellings = new SellingDAO().getByInvoice(invoice);
        DefaultTableModel model = (DefaultTableModel) tblInvoiceUnit.getModel();

        for (int i = 0; i < sellings.size(); i++) {
         Vector v = new Vector();
            v.add(sellings.get(i).getMedicineCode());
            v.add(sellings.get(i).getMedicineName());
            v.add(sellings.get(i).getMedicineQuantity());
            v.add(sellings.get(i).getSalesSellingPrice());
            v.add(sellings.get(i).getMedicineQuantity() * sellings.get(i).getSalesSellingPrice());
//            v.add(sellings.get(i).getMedicineTotalAmounnt());
          model.addRow(v);
        }
        
        }
private void showProduct() {
//        s = new Selling();
//        DefaultTableModel model = (DefaultTableModel) invoiceInfoTable.getModel();
//            Vector v = new Vector();
//            v.add(s.getProductCode());
//            v.add(s.getProductName());
//            v.add(s.getProductQty());
//            v.add(s.getPrice());
//            tQty += pQuantity;
//            totalQty.setText(String.valueOf(tQty));
//            v.add((p.getSellingCost() * pQuantity));
//            tprice += (p.getSellingCost() * pQuantity);
//            model.addRow(v);
//            totalPrice.setText(String.valueOf(tprice));

        List<SellingPerUnit> selling = new SellingDAO().getByInvoice(invoice);
        String[] columnNames = {"Code", "Name", "Quantity", "Price", "Total"};
        Object[][] data = new Object[selling.size()][5];
        for (int i = 0; i < selling.size(); i++) {
            SellingPerUnit s = selling.get(i);
            Object[] o = {s.getMedicineCode(), s.getMedicineName(), s.getMedicineQuantity(), s.getSalesSellingPrice(), s.getMedicineTotalAmounnt()};
            for (int j = 0; j < 8; j++) {
                data[i][j] = o[j];
                System.out.println("inv" + s.getMedicineCode());
            }
        }
        DefaultTableModel model = new DefaultTableModel(data, columnNames);
        tblInvoiceUnit.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoiceUnit = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblInvoiceUnit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInvoiceUnit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceUnit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInvoiceUnit;
    // End of variables declaration//GEN-END:variables
}
